services:
  blog:
    build:
      context: .
      dockerfile: Dockerfile
    image: blog:latest
    container_name: blog
    ports:
      - "8084:8083"
    environment:
      - PORT=:8083
      - SITE_NAME=技术博客
      - PAGE_SIZE=10
      - POSTS_DIR=/app/posts
    volumes:
      - ./posts:/app/posts
      - ./templates:/app/templates
      - ./static:/app/static
      - /etc/localtime:/etc/localtime
    restart: always
